import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { ClerkProvider } from "@clerk/nextjs";
import { shadesOfPurple } from "@clerk/themes";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider
    appearance={{
      baseTheme:shadesOfPurple,   //use npm i @clerk/themes for the background
      variables:{
        colorPrimary: "#3b82f6",
        colorBackground: "#1a202c",
        colorInputBackground: "#2D3748",
        colorInputText: "#F3F3F6",
      },
      elements:{
        formButtonPrimary:"bg-red-800 hover:bg-red-700 text-white",
        card:"bg-gray-800",
        headerTitle: "text-blue-400"
      }
    }}
    >
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className} dotted-background`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
        >
          {/* header */}
          <Header />
          <main className="min-h-screen">{children}</main>
          <Toaster richColors />
          {/* footer */}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
    </ClerkProvider>
  );
}
